# Generated by Django 3.2.5 on 2021-07-08 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pk', models.IntegerField(blank=True)),
                ('dept', models.CharField(choices=[('mju', 'MJU'), ('uplex', 'UPLEX'), ('not-specified', 'Not Specified')], max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=500)),
                ('nickname', models.CharField(blank=True, max_length=200)),
                ('message', models.CharField(max_length=100, null=True)),
                ('zonecode', models.CharField(default=0, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
